### ISSUE TITLE
Filldown brush fails below Y=0 [BUG] 

### ISSUE THREAD

**Issue by Klime65536** [KevinDaGame/VoxelSniper-Reimagined#237]
**Describe the bug**
The filldown brush always stops when Y=0 regardless of the actual bottom limit of the world or how far down the next surface is. Right clicking blocks below Y=0 does nothing, blocks at 0 or above produce a weird "lid" of material which stops at Y=0.

**To Reproduce**
1. Load into a world (preferably superflat) with a minimum height value below 0.
2. Set up some basic terrain with some above 0, some below 0
3. Use /b fd to try to fill the areas below Y=0 with any material
4. Confirm that the brush will never modify blocks with a y value <0

**Expected behavior**
The filldown brush should fill down to either the nearest surface or the world bottom regardless of the dimension's minimum height.

**Desktop (please complete the following information):**
 - Minecraft version: 1.20.1
 - Voxelsniper version: 8.13.0
 - Server/client software: Spigot

**Comment by KevinDaGame** [comment]
Thanks for the report. I will try to look into it soon

**Comment by KevinDaGame** [comment]
@Klime65536 This should be resolved in #238. This jar contains the fix. To ensure it is fixed, could you run this jar to see if it resolves your issue?
(The jar is zipped because github doesn't allow uploading jars in comments)
[voxelsniper-8.13.1-beta-spigot.zip](https://github.com/KevinDaGame/VoxelSniper-Reimagined/files/14958114/voxelsniper-8.13.1-beta-spigot.zip)

**Comment by KevinDaGame** [comment]
Glad to hear it. That jar is safe to continue using. I will attempt to put out an official release over the weekend
